// src/app/_components/BackgroundAnimation.tsx
'use client';

import { useState, useEffect } from 'react';

export default function BackgroundAnimation() {
  const [bgAnimation, setBgAnimation] = useState({
    mobileSize: 768,
    bgOverlayPosition: {
      x: 0,
      y: 0,
    },
    mouseMoveStarted: false,
  });

  // Handle mouse movement events
  const handleMouseMove = (e: MouseEvent) => {
    setBgAnimation({
      ...bgAnimation,
      bgOverlayPosition: {
        x: e.clientX + window.scrollX,
        y: e.clientY + window.scrollY,
      },
    });
  };

  // Add and remove event listener based on window size on mount and resize
  useEffect(() => {
    const handleResize = () => {
      if (window.innerWidth >= bgAnimation.mobileSize) {
        window.addEventListener('mousemove', handleMouseMove);
      } else {
        window.removeEventListener('mousemove', handleMouseMove);
        setBgAnimation({
          ...bgAnimation,
          bgOverlayPosition: { x: 0, y: 0 },
          mouseMoveStarted: false, // Reset mouse move state
        });
      }
    };

    handleResize();

    // Cleanup function to remove event listener on unmount
    return () => window.removeEventListener('resize', handleResize);
  }, [bgAnimation.mobileSize]); // Dependency array for resize check

  return (
    <div className="background">
      <div className="background__overlay-bg"
        style={{
          left: `${bgAnimation.bgOverlayPosition.x - 100}px`,
          top: `${bgAnimation.bgOverlayPosition.y - 100}px`
        }}></div>
    </div>
  );
}

// src/components/BackgroundAnimation.vue
<script lang="ts">
import { onMounted } from 'vue';


export default {
  name: 'Background Animation',
  data() {
    return {
      mobileSize: 768,
      bgOverlayPosition: {
        x: 0,
        y: 0
      },
      mouseMoveStarted: false
    }
  },

  mounted() {
    if (window.innerWidth >= this.mobileSize) {
      window.addEventListener('mousemove', this.handleMouseMove)
    }

    window.addEventListener('resize', () => {
      if (window.innerWidth >= this.mobileSize) {
        window.addEventListener('mousemove', this.handleMouseMove)
      } else {
        window.removeEventListener('mousemove', this.handleMouseMove)
        this.bgOverlayPosition.x = 0;
        this.bgOverlayPosition.y = 0;
      }
    })
  },

  methods: {
    handleMouseMove(e: any) {
      setTimeout(() => {
        this.bgOverlayPosition.x = e.clientX + window.scrollX
        this.bgOverlayPosition.y = e.clientY + window.scrollY
      }, this.mouseMoveStarted ? 60 : 0)
      this.mouseMoveStarted = true;
    },
  },

}

</script>

<template>
  <div class="background">
    <!-- <div class="background__mobile">
      <div class="background__mobile__bg-1"></div>
      <div class="background__mobile__bg-2"></div>
    </div> -->
    <div v-show="mouseMoveStarted"
         class="background__overlay-bg"
         :style="{ left: (bgOverlayPosition.x - 100) + 'px', top: (bgOverlayPosition.y - 100) + 'px' }">
    </div>
  </div>
</template>
