// src/app/_components/Navigation.tsx
'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';

function Navigation() {
  const pathName = usePathname();
  const [opacity, setOpacity] = useState(1); // State for navigation opacity

  const menuToggle = 30;

  useEffect(() => {
    const handleScroll = () => {
      const positionY = window.scrollY;
      const newOpacity = positionY > menuToggle ? 0 : 1;

      if (opacity !== newOpacity) { // Only update if opacity has changed
        setOpacity(newOpacity);
      }
    };

    window.addEventListener('scroll', handleScroll);

    return () => window.removeEventListener('scroll', handleScroll); // Cleanup
  }, [opacity, menuToggle]); // Dependency array optimization

  return (
    <nav className="navigation" style={{ opacity }}>
      <ul>
        <li>
          <Link href="/" className={pathName === '/home' ? 'active-route' : ''} >Home</Link>
        </li>
        <li>
          <Link href="/about-me" className={pathName === '/about-me' ? 'active-route' : ''}>About</Link>
        </li>
        <li>
          <Link href="/work" className={pathName === '/work' ? 'active-route' : ''}>Work</Link>
        </li>
      </ul>
    </nav>
  );
}

export default Navigation;

// src/components/Navigation.vue
<template>
  <nav class="navigation">
    <ul>
      <li>
        <router-link to="/">Home</router-link>
      </li>
      <li>
        <router-link to="/work">Work</router-link>
      </li>
      <li>
        <router-link to="/about-me">About</router-link>
      </li>
    </ul>
  </nav>
</template>

<script>
export default {
  mounted() {
    const nav = document.querySelector('.navigation');
    const menuToggle = 110;

    let cache = null;
    window.addEventListener('scroll', (e) => {
      if (!cache) {
        setTimeout(() => {
          // Add all the code
          const positionY = window.pageYOffset;
          if (positionY > menuToggle) {
            nav.style.opacity = '0';
          } else {
            nav.style.opacity = '1';
          }
          cache = null;
        }, 300);
        cache = e;
      }
    });
  },
};

</script>
